# permissions for end users to edit devicevisitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceaccess-editor-role
rules:
- apiGroups:
  - devices.kubeedge.io
  resources:
  - deviceaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.kubeedge.io
  resources:
  - deviceaccesses/status
  verbs:
  - get
