# permissions for end users to edit deviceprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicemodel-editor-role
rules:
- apiGroups:
  - devices.kubeedge.io
  resources:
  - devicemodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devices.kubeedge.io
  resources:
  - devicemodels/status
  verbs:
  - get
