# permissions for end users to view deviceprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicemodel-viewer-role
rules:
- apiGroups:
  - devices.kubeedge.io
  resources:
  - devicemodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.kubeedge.io
  resources:
  - devicemodels/status
  verbs:
  - get
