# permissions for end users to view devicevisitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceaccesses-viewer-role
rules:
- apiGroups:
  - devices.kubeedge.io
  resources:
  - deviceaccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devices.kubeedge.io
  resources:
  - deviceaccesses/status
  verbs:
  - get
