apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: edgex-device-virtual
    sys: edgex
  name: edgex-device-virtual
  namespace: kubeedge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgex-device-virtual
  template:
    metadata:
      labels:
        app: edgex-device-virtual
    spec:
      hostname: edgex-device-virtual
      containers:
        - image: edgexfoundry/device-virtual:2.0.0
          name: edgex-device-virtual
          env:
            - name: CLIENTS_CORE_COMMAND_HOST
              value: edgex-core-command
            - name: CLIENTS_CORE_DATA_HOST
              value: edgex-core-data
            - name: CLIENTS_CORE_METADATA_HOST
              value: edgex-core-metadata
            - name: CLIENTS_SUPPORT_NOTIFICATIONS_HOST
              value: edgex-support-notifications
            - name: CLIENTS_SUPPORT_SCHEDULER_HOST
              value: edgex-support-scheduler
            - name: DATABASES_PRIMARY_HOST
              value: edgex-redis
            - name: EDGEX_SECURITY_SECRET_STORE
              value: "false"
            - name: MESSAGEQUEUE_HOST
              value: edgex-redis
            - name: REGISTRY_HOST
              value: edgex-core-consul
            - name: SERVICE_HOST
              value: edgex-device-virtual
          ports:
            - containerPort: 59900
              hostPort: 59900

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: edgex-device-virtual
    sys: edgex
  name: edgex-device-virtual
  namespace: kubeedge
spec:
  ports:
    - name: http-0
      port: 59900
      targetPort: 59900
      protocol: TCP
  selector:
    app: edgex-device-virtual


